# Generated by Django 3.1 on 2020-08-23 14:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('preparation_mode', models.CharField(max_length=300)),
                ('time_mode', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Yield', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('date_of_created', models.DateField(default=datetime.datetime(2020, 8, 23, 11, 49, 34, 977925))),
            ],
        ),
    ]
