# Generated by Django 3.1 on 2020-09-22 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=300)),
                ('date_of_created', models.DateField(blank=True, default=datetime.datetime(2020, 9, 22, 18, 10, 54, 627645))),
                ('time_preparation', models.TimeField()),
                ('category', models.CharField(choices=[('PA', 'Pasta'), ('VE', 'Vegan'), ('CA', 'Candy')], max_length=2)),
            ],
        ),
    ]
