# Generated by Django 3.1 on 2020-08-23 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_mode',
            new_name='time_preparation',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_of_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 23, 16, 3, 58, 373625)),
        ),
    ]
