# Generated by Django 3.1 on 2020-09-22 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_of_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 22, 18, 10, 58, 142301)),
        ),
    ]
