# Generated by Django 3.1 on 2020-09-22 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20200922_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('PA', 'Pasta'), ('WI', 'Without'), ('VE', 'Vegan'), ('CA', 'Candy')], default='WI', max_length=2),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_of_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 22, 18, 20, 26, 142969)),
        ),
    ]
