# Generated by Django 3.1 on 2020-09-23 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200922_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_of_created',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 9, 23, 11, 52, 12, 47918)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time_preparation',
            field=models.DurationField(),
        ),
    ]
